### ISSUE TITLE
Add ability to delete hosts that already exist in current config

### ISSUE THREAD

**Issue by L1ghtman2k** [cse442-spring-2020-offering/cse442-semester-project-ubnetdef#70]
### Story:
As a system administrator or a penetration tester, I want to be able to delete the existing hosts from the current configuration, so I can remove hosts that are not in the target deployment range

### Task test:

- [ ]  Click `Ctrl+X` to open the menu
- [ ]  Navigate to `Remote Hosts` Menu
- [ ]  Navigate to `Add or Edit Hosts`
- [ ]  Enter `192.168.1.1` for the first field
- [ ]  Select `ssh` as a remoting method
- [ ]  Click `Save`
- [ ]  Click `Ctrl+X` to open the menu
- [ ]  Navigate to `Remote Hosts` Menu
- [ ]  Navigate to `Add or Edit Hosts`
- [ ]  Enter `192.168.1.1` for the first field
- [ ]  Make sure a button titled `Delete Host(s)` appears
- [ ]  Click the button, and confirm the pop up
- [ ]  Make sure the host doesn't appear on main screen's `Host(s) availiable` section
